yolo_test/config/routes.rb
#root 'welcome#index'
Rails.application.routes.draw do 
  get 'message/:user_entry', to: 'message#show'
  get 'static_pages/home'
  get 'static_pages/contact', to: 'controller#contact'
  get 'politique-de-confidentialite', to: 'static_pages/home#privacy_policy', as: 'privacy_policy'
end

yolo_test/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

yolo_test/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

yolo_test/app/controllers/message_controller.rb
class MessageController < ApplicationController
  def show
    puts "$" * 60
    puts "Voici le message de l'URL :"
    puts params[:user_entry]
    puts "$" * 60
  end
end

yolo_test/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

yolo_test/app/helpers/application_helper.rb
module ApplicationHelper
end

yolo_test/app/helpers/message_helper.rb
module MessageHelper
end

yolo_test/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

yolo_test/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoloTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

yolo_test/app/views/message/show.html.erb
<h1>Message#show</h1>
<p>Find me in app/views/message/show.html.erb</p>
<%=link_to "clique ici", static_pages_home_path %>

yolo_test/app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<%=link_to "clique ici", static_pages_home_path %>
<%=link_to "lance", asset_path %>